environment:
  name: prod
  project: cdf-bootcamp-05-prod
  validation-type: prod
  selected:
  - modules/bootcamp/data_foundation/
  - modules/bootcamp/ice_cream_api/
  - modules/bootcamp/use_cases/oee/

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      data_foundation:
        data_developer_source_id: ${DATA_DEVELOPER_SOURCE_ID}

      ice_cream_api:
        icapi_extractors_source_id: ${ICAPI_EXTRACTORS_SOURCE_ID}
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

      use_cases:
        oee:
          data_pipeline_oee_source_id: ${DATA_PIPELINE_OEE_SOURCE_ID}
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}

    cdf_common:
      dataset: ingestion
      instanceSpace: springfield_instances
      directRelationJob: ctx_files_direct_relation_write
      rawSourceDatabase: ingestion
      rawStateDatabase: contextualizationState
      rawStateTable: diagramParsing
      schemaSpace: cdf_cdm
      annotationSpace: springfield_instances

    cdf_ingestion:
      workflow: ingestion
      groupSourceId: <not set>
      ingestionClientId: ${INGESTION_CLIENT_ID}
      ingestionClientSecret: ${INGESTION_CLIENT_SECRET}
      assetTransformationExternalId: sap_assets_springfield_s4hana
      equipmentTransformationExternalId: sap_equipment_springfield_s4hana
      equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
      timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
      maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
      operationTransformationExternalId: sap_operations_springfield_s4hana
      operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
      fileTransformationExternalId: files_metadata_springfield
      activityToAssetTransformationExternalId: activity_to_asset
      activityToEquipmentTransformationExternalId: activity_to_equipment
      activityToTimeSeriesTransformationExternalId: activity_to_timeseries
      timeSeriesToAssetTransformationExternalId: timeseries_to_asset
      timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
      pandidContextualizationFunction: contextualization_p_and_id_annotater
      contextualization_connection_writer: contextualization_connection_writer
      dataset: ingestion
      rawSourceDatabase: ingestion
      rawStateDatabase: contextualizationState
      schemaSpace: sp_enterprise_process_industry
      schemaSpace2: cdf_cdm
      schemaSpace3: cdf_idm
      instanceSpaces:
      - springfield_instances
      - cdf_cdm_units
      runWorkflowUserIds:
      - <your user id>

    contextualization:
      cdf_connection_sql:
        activityToAssetTransformationExternalId: activity_to_asset
        activityToEquipmentTransformationExternalId: activity_to_equipment
        activityToTimeSeriesTransformationExternalId: activity_to_timeseries
        timeSeriesToAssetTransformationExternalId: timeseries_to_asset
        timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
        dataset: ingestion
        instanceSpace: springfield_instances
        schemaSpace: cdf_cdm
        groupSourceId: <not set>

      cdf_p_and_id_parser:
        contextualizationId: p_and_id_parser
        contextualizationName: P&ID Parser
        annotatorJob: ctx_files_pandid_annotater
        dataset: ingestion
        schemaSpace: cdf_cdm
        annotationSpace: springfield_instances
        instanceSpaces:
        - springfield_instances
        groupSourceId: <not set>
        workflow: p_and_id_parser
        workflowClientId: ${P_AND_ID_PARSER_CLIENT_ID}
        workflowClientSecret: ${P_AND_ID_PARSER_CLIENT_SECRET}

    industrial_tools:
      cdf_search:
        location: springfield
        locationName: Springfield
        instanceSpace: springfield_instances

    models:
      cdf_process_industry_extension:
        organization: YourOrg
        schemaSpace: sp_enterprise_process_industry

    sourcesystem:
      cdf_pi:
        sourceName: Springfield AVEVA PI
        sourceId: springfield_aveva_pi
        timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
        dataset: ingestion
        rawSourceDatabase: ingestion
        instanceSpace: springfield_instances
        organization: YourOrg
        schemaSpace: sp_enterprise_process_industry
        groupSourceId: <not set>
        workflow: aveva_pi_population # can also contain location aveva_pi_springfield_population
        workflowClientId: ${AVEVA_PI_SPRINGFIELD_CLIENT_ID}
        workflowClientSecret: ${AVEVA_PI_SPRINGFIELD_CLIENT_SECRET}

      cdf_sap_assets:
        sourceName: SAP Springfield S/4HANA Assets
        sourceId: sap_springfield_s4hana_assets
        assetTransformationExternalId: sap_assets_springfield_s4hana
        equipmentTransformationExternalId: sap_equipment_springfield_s4hana
        equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
        dataset: ingestion
        rawSourceDatabase: ingestion
        instanceSpace: springfield_instances
        organization: YourOrg
        schemaSpace: sp_enterprise_process_industry
        groupSourceId: <not set>
        workflow: sap_s4hana_population # can also contain location sap_springfield_s4hana_population
        workflowClientId: ${SAP_SPRINGFIELD_S4HANA_CLIENT_ID}
        workflowClientSecret: ${SAP_SPRINGFIELD_S4HANA_CLIENT_SECRET}

      cdf_sap_events:
        sourceName: SAP Springfield S/4HANA Activities
        sourceId: sap_springfield_s4hana_activities
        maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
        operationTransformationExternalId: sap_operations_springfield_s4hana
        operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
        dataset: ingestion
        rawSourceDatabase: ingestion
        instanceSpace: springfield_instances
        organization: YourOrg
        schemaSpace: sp_enterprise_process_industry
        workflow: sap_s4hana_population_events # can also contain location sap_springfield_s4hana_population
        groupSourceId: <not set>
        workflowClientId: ${SAP_SPRINGFIELD_S4HANA_CLIENT_ID}
        workflowClientSecret: ${SAP_SPRINGFIELD_S4HANA_CLIENT_SECRET}

      cdf_sharepoint:
        sourceName: Springfield Sharepoint
        sourceId: springfield_sharepoint
        fileTransformationExternalId: files_metadata_springfield
        dataset: ingestion
        rawSourceDatabase: ingestion
        instanceSpace: springfield_instances
        groupSourceId: <not set>
        organization: YourOrg
        schemaSpace: sp_enterprise_process_industry
        workflow: files_metadata_population # can also contain location files_metadata_springfield_population
        workflowClientId: ${SHAREPOINT_SERVICE_PRINCIPAL_CLIENT_ID}
        workflowClientSecret: ${SHAREPOINT_SERVICE_PRINCIPAL_CLIENT_SECRET}
